#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'spring-boot-app'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:7865'] # Change to your Spring Boot app's host and port
